# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NX_xeb4ZXGyO8-q63CKLrZFqaYWecxfB
"""

import pandas as pd
df =pd.DataFrame({'Ism': ['Zarnigorbegim', 'Farogatxon', 'Umidaxon','Muhbiraxon','Sarvinoz','Mahliyoxon','Mohlaroyim','Mubinabonu','Barchinoy','Solihabonu'    ],
                  'Familiya':['Ahmadaliyeva','Adhamova','Begaliyeva','Yolchiyeva','Abdurasulova','Sulaymonova','Murodjonova','Siddiqova','Shamsiddinova','Kamolova'    ],
                  'Yoshi':['19','19','19','20','19','19','19','19','17','1'   ],
                  'Kursi': ['2','2','2','2','2','2','2','2','2','2'   ]
                   })
print(df)

df.to_excel('guruh.xlsx', index =False , sheet_name='Sheet1')